/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import * as axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { AccountSettingsDto, ProblemDetails, UpdateAccountSettingsRequest, ValidationProblemDetails } from './..';

/**
 * @summary Returns account settings for the current authenticated user.
If settings do not exist yet, they are created with defaults.
 */
export const getApiSettingsAccount = (options?: AxiosRequestConfig): Promise<AxiosResponse<AccountSettingsDto>> => {
  return axios.default.get(`/api/settings/account`, options);
};

export const getGetApiSettingsAccountQueryKey = () => {
  return [`/api/settings/account`] as const;
};

export const getGetApiSettingsAccountQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiSettingsAccount>>,
  TError = AxiosError<ProblemDetails>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingsAccount>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiSettingsAccountQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSettingsAccount>>> = ({ signal }) =>
    getApiSettingsAccount({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiSettingsAccount>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiSettingsAccountQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSettingsAccount>>>;
export type GetApiSettingsAccountQueryError = AxiosError<ProblemDetails>;

export function useGetApiSettingsAccount<
  TData = Awaited<ReturnType<typeof getApiSettingsAccount>>,
  TError = AxiosError<ProblemDetails>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingsAccount>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettingsAccount>>,
          TError,
          Awaited<ReturnType<typeof getApiSettingsAccount>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiSettingsAccount<
  TData = Awaited<ReturnType<typeof getApiSettingsAccount>>,
  TError = AxiosError<ProblemDetails>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingsAccount>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettingsAccount>>,
          TError,
          Awaited<ReturnType<typeof getApiSettingsAccount>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiSettingsAccount<
  TData = Awaited<ReturnType<typeof getApiSettingsAccount>>,
  TError = AxiosError<ProblemDetails>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingsAccount>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Returns account settings for the current authenticated user.
If settings do not exist yet, they are created with defaults.
 */

export function useGetApiSettingsAccount<
  TData = Awaited<ReturnType<typeof getApiSettingsAccount>>,
  TError = AxiosError<ProblemDetails>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingsAccount>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiSettingsAccountQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Updates the account settings for the current authenticated user.
 */
export const putApiSettingsAccount = (
  updateAccountSettingsRequest: UpdateAccountSettingsRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<AccountSettingsDto>> => {
  return axios.default.put(`/api/settings/account`, updateAccountSettingsRequest, options);
};

export const getPutApiSettingsAccountMutationOptions = <
  TError = AxiosError<ValidationProblemDetails | ProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiSettingsAccount>>,
    TError,
    { data: UpdateAccountSettingsRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiSettingsAccount>>,
  TError,
  { data: UpdateAccountSettingsRequest },
  TContext
> => {
  const mutationKey = ['putApiSettingsAccount'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiSettingsAccount>>,
    { data: UpdateAccountSettingsRequest }
  > = (props) => {
    const { data } = props ?? {};

    return putApiSettingsAccount(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiSettingsAccountMutationResult = NonNullable<Awaited<ReturnType<typeof putApiSettingsAccount>>>;
export type PutApiSettingsAccountMutationBody = UpdateAccountSettingsRequest;
export type PutApiSettingsAccountMutationError = AxiosError<ValidationProblemDetails | ProblemDetails>;

/**
 * @summary Updates the account settings for the current authenticated user.
 */
export const usePutApiSettingsAccount = <
  TError = AxiosError<ValidationProblemDetails | ProblemDetails>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiSettingsAccount>>,
      TError,
      { data: UpdateAccountSettingsRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiSettingsAccount>>,
  TError,
  { data: UpdateAccountSettingsRequest },
  TContext
> => {
  return useMutation(getPutApiSettingsAccountMutationOptions(options), queryClient);
};
