/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import { useMutation } from '@tanstack/react-query';
import type { MutationFunction, QueryClient, UseMutationOptions, UseMutationResult } from '@tanstack/react-query';

import * as axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  ApiErrorDto,
  BatchDecisionRequest,
  BatchDecisionResultDto,
  BatchIgnoreResult,
  ProblemDetails,
  ReplyListItemDtoPagedResult,
  SearchSuggestedRepliesRequest,
  ValidationProblemDetails,
} from './..';

/**
 * @summary Searches suggested replies for the replies page.
 */
export const postApiRepliesSuggestedSearch = (
  searchSuggestedRepliesRequest: SearchSuggestedRepliesRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ReplyListItemDtoPagedResult>> => {
  return axios.default.post(`/api/replies/suggested/search`, searchSuggestedRepliesRequest, options);
};

export const getPostApiRepliesSuggestedSearchMutationOptions = <
  TError = AxiosError<ApiErrorDto>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiRepliesSuggestedSearch>>,
    TError,
    { data: SearchSuggestedRepliesRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiRepliesSuggestedSearch>>,
  TError,
  { data: SearchSuggestedRepliesRequest },
  TContext
> => {
  const mutationKey = ['postApiRepliesSuggestedSearch'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiRepliesSuggestedSearch>>,
    { data: SearchSuggestedRepliesRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiRepliesSuggestedSearch(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiRepliesSuggestedSearchMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiRepliesSuggestedSearch>>
>;
export type PostApiRepliesSuggestedSearchMutationBody = SearchSuggestedRepliesRequest;
export type PostApiRepliesSuggestedSearchMutationError = AxiosError<ApiErrorDto>;

/**
 * @summary Searches suggested replies for the replies page.
 */
export const usePostApiRepliesSuggestedSearch = <TError = AxiosError<ApiErrorDto>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiRepliesSuggestedSearch>>,
      TError,
      { data: SearchSuggestedRepliesRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiRepliesSuggestedSearch>>,
  TError,
  { data: SearchSuggestedRepliesRequest },
  TContext
> => {
  return useMutation(getPostApiRepliesSuggestedSearchMutationOptions(options), queryClient);
};
export const deleteApiRepliesId = (id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.default.delete(`/api/replies/${id}`, options);
};

export const getDeleteApiRepliesIdMutationOptions = <
  TError = AxiosError<ProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiRepliesId>>, TError, { id: string }, TContext>;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteApiRepliesId>>, TError, { id: string }, TContext> => {
  const mutationKey = ['deleteApiRepliesId'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiRepliesId>>, { id: string }> = (props) => {
    const { id } = props ?? {};

    return deleteApiRepliesId(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiRepliesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiRepliesId>>>;

export type DeleteApiRepliesIdMutationError = AxiosError<ProblemDetails>;

export const useDeleteApiRepliesId = <TError = AxiosError<ProblemDetails>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiRepliesId>>, TError, { id: string }, TContext>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteApiRepliesId>>, TError, { id: string }, TContext> => {
  return useMutation(getDeleteApiRepliesIdMutationOptions(options), queryClient);
};
/**
 * @summary Approves batch of replies
 */
export const postApiRepliesApprove = (
  batchDecisionRequest: BatchDecisionRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<BatchDecisionResultDto>> => {
  return axios.default.post(`/api/replies/approve`, batchDecisionRequest, options);
};

export const getPostApiRepliesApproveMutationOptions = <
  TError = AxiosError<ValidationProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiRepliesApprove>>,
    TError,
    { data: BatchDecisionRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiRepliesApprove>>,
  TError,
  { data: BatchDecisionRequest },
  TContext
> => {
  const mutationKey = ['postApiRepliesApprove'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiRepliesApprove>>,
    { data: BatchDecisionRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiRepliesApprove(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiRepliesApproveMutationResult = NonNullable<Awaited<ReturnType<typeof postApiRepliesApprove>>>;
export type PostApiRepliesApproveMutationBody = BatchDecisionRequest;
export type PostApiRepliesApproveMutationError = AxiosError<ValidationProblemDetails>;

/**
 * @summary Approves batch of replies
 */
export const usePostApiRepliesApprove = <TError = AxiosError<ValidationProblemDetails>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiRepliesApprove>>,
      TError,
      { data: BatchDecisionRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiRepliesApprove>>,
  TError,
  { data: BatchDecisionRequest },
  TContext
> => {
  return useMutation(getPostApiRepliesApproveMutationOptions(options), queryClient);
};
export const postApiRepliesBatchIgnore = (
  postApiRepliesBatchIgnoreBody: string[],
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<BatchIgnoreResult>> => {
  return axios.default.post(`/api/replies/batch-ignore`, postApiRepliesBatchIgnoreBody, options);
};

export const getPostApiRepliesBatchIgnoreMutationOptions = <
  TError = AxiosError<ProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiRepliesBatchIgnore>>,
    TError,
    { data: string[] },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof postApiRepliesBatchIgnore>>, TError, { data: string[] }, TContext> => {
  const mutationKey = ['postApiRepliesBatchIgnore'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiRepliesBatchIgnore>>, { data: string[] }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return postApiRepliesBatchIgnore(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiRepliesBatchIgnoreMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiRepliesBatchIgnore>>
>;
export type PostApiRepliesBatchIgnoreMutationBody = string[];
export type PostApiRepliesBatchIgnoreMutationError = AxiosError<ProblemDetails>;

export const usePostApiRepliesBatchIgnore = <TError = AxiosError<ProblemDetails>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiRepliesBatchIgnore>>,
      TError,
      { data: string[] },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postApiRepliesBatchIgnore>>, TError, { data: string[] }, TContext> => {
  return useMutation(getPostApiRepliesBatchIgnoreMutationOptions(options), queryClient);
};
