/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import * as axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  ApplicationConfigurationDto,
  CreateApplicationConfigurationRequest,
  ProblemDetails,
  UpdateApplicationConfigurationRequest,
} from './..';

/**
 * @summary Gets all application configurations.
 */
export const getApiApplicationConfigurations = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApplicationConfigurationDto[]>> => {
  return axios.default.get(`/api/application-configurations`, options);
};

export const getGetApiApplicationConfigurationsQueryKey = () => {
  return [`/api/application-configurations`] as const;
};

export const getGetApiApplicationConfigurationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiApplicationConfigurations>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiApplicationConfigurations>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiApplicationConfigurationsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiApplicationConfigurations>>> = ({ signal }) =>
    getApiApplicationConfigurations({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiApplicationConfigurations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiApplicationConfigurationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiApplicationConfigurations>>
>;
export type GetApiApplicationConfigurationsQueryError = AxiosError<unknown>;

export function useGetApiApplicationConfigurations<
  TData = Awaited<ReturnType<typeof getApiApplicationConfigurations>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiApplicationConfigurations>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiApplicationConfigurations>>,
          TError,
          Awaited<ReturnType<typeof getApiApplicationConfigurations>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiApplicationConfigurations<
  TData = Awaited<ReturnType<typeof getApiApplicationConfigurations>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiApplicationConfigurations>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiApplicationConfigurations>>,
          TError,
          Awaited<ReturnType<typeof getApiApplicationConfigurations>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiApplicationConfigurations<
  TData = Awaited<ReturnType<typeof getApiApplicationConfigurations>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiApplicationConfigurations>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Gets all application configurations.
 */

export function useGetApiApplicationConfigurations<
  TData = Awaited<ReturnType<typeof getApiApplicationConfigurations>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiApplicationConfigurations>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiApplicationConfigurationsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Creates a new application configuration.
 */
export const postApiApplicationConfigurations = (
  createApplicationConfigurationRequest: CreateApplicationConfigurationRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApplicationConfigurationDto>> => {
  return axios.default.post(`/api/application-configurations`, createApplicationConfigurationRequest, options);
};

export const getPostApiApplicationConfigurationsMutationOptions = <
  TError = AxiosError<ProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiApplicationConfigurations>>,
    TError,
    { data: CreateApplicationConfigurationRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiApplicationConfigurations>>,
  TError,
  { data: CreateApplicationConfigurationRequest },
  TContext
> => {
  const mutationKey = ['postApiApplicationConfigurations'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiApplicationConfigurations>>,
    { data: CreateApplicationConfigurationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiApplicationConfigurations(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiApplicationConfigurationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiApplicationConfigurations>>
>;
export type PostApiApplicationConfigurationsMutationBody = CreateApplicationConfigurationRequest;
export type PostApiApplicationConfigurationsMutationError = AxiosError<ProblemDetails>;

/**
 * @summary Creates a new application configuration.
 */
export const usePostApiApplicationConfigurations = <TError = AxiosError<ProblemDetails>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiApplicationConfigurations>>,
      TError,
      { data: CreateApplicationConfigurationRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiApplicationConfigurations>>,
  TError,
  { data: CreateApplicationConfigurationRequest },
  TContext
> => {
  return useMutation(getPostApiApplicationConfigurationsMutationOptions(options), queryClient);
};
/**
 * @summary Gets an application configuration by key.
 */
export const getByKeyAsync = (
  key: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApplicationConfigurationDto>> => {
  return axios.default.get(`/api/application-configurations/${key}`, options);
};

export const getGetByKeyAsyncQueryKey = (key: string) => {
  return [`/api/application-configurations/${key}`] as const;
};

export const getGetByKeyAsyncQueryOptions = <
  TData = Awaited<ReturnType<typeof getByKeyAsync>>,
  TError = AxiosError<ProblemDetails>,
>(
  key: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getByKeyAsync>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetByKeyAsyncQueryKey(key);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getByKeyAsync>>> = ({ signal }) =>
    getByKeyAsync(key, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!key, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getByKeyAsync>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetByKeyAsyncQueryResult = NonNullable<Awaited<ReturnType<typeof getByKeyAsync>>>;
export type GetByKeyAsyncQueryError = AxiosError<ProblemDetails>;

export function useGetByKeyAsync<
  TData = Awaited<ReturnType<typeof getByKeyAsync>>,
  TError = AxiosError<ProblemDetails>,
>(
  key: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getByKeyAsync>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getByKeyAsync>>,
          TError,
          Awaited<ReturnType<typeof getByKeyAsync>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetByKeyAsync<
  TData = Awaited<ReturnType<typeof getByKeyAsync>>,
  TError = AxiosError<ProblemDetails>,
>(
  key: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getByKeyAsync>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getByKeyAsync>>,
          TError,
          Awaited<ReturnType<typeof getByKeyAsync>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetByKeyAsync<
  TData = Awaited<ReturnType<typeof getByKeyAsync>>,
  TError = AxiosError<ProblemDetails>,
>(
  key: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getByKeyAsync>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Gets an application configuration by key.
 */

export function useGetByKeyAsync<
  TData = Awaited<ReturnType<typeof getByKeyAsync>>,
  TError = AxiosError<ProblemDetails>,
>(
  key: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getByKeyAsync>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetByKeyAsyncQueryOptions(key, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Updates an existing application configuration.
 */
export const putApiApplicationConfigurationsKey = (
  key: string,
  updateApplicationConfigurationRequest: UpdateApplicationConfigurationRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApplicationConfigurationDto>> => {
  return axios.default.put(`/api/application-configurations/${key}`, updateApplicationConfigurationRequest, options);
};

export const getPutApiApplicationConfigurationsKeyMutationOptions = <
  TError = AxiosError<ProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiApplicationConfigurationsKey>>,
    TError,
    { key: string; data: UpdateApplicationConfigurationRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiApplicationConfigurationsKey>>,
  TError,
  { key: string; data: UpdateApplicationConfigurationRequest },
  TContext
> => {
  const mutationKey = ['putApiApplicationConfigurationsKey'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiApplicationConfigurationsKey>>,
    { key: string; data: UpdateApplicationConfigurationRequest }
  > = (props) => {
    const { key, data } = props ?? {};

    return putApiApplicationConfigurationsKey(key, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiApplicationConfigurationsKeyMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiApplicationConfigurationsKey>>
>;
export type PutApiApplicationConfigurationsKeyMutationBody = UpdateApplicationConfigurationRequest;
export type PutApiApplicationConfigurationsKeyMutationError = AxiosError<ProblemDetails>;

/**
 * @summary Updates an existing application configuration.
 */
export const usePutApiApplicationConfigurationsKey = <TError = AxiosError<ProblemDetails>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiApplicationConfigurationsKey>>,
      TError,
      { key: string; data: UpdateApplicationConfigurationRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiApplicationConfigurationsKey>>,
  TError,
  { key: string; data: UpdateApplicationConfigurationRequest },
  TContext
> => {
  return useMutation(getPutApiApplicationConfigurationsKeyMutationOptions(options), queryClient);
};
/**
 * @summary Deletes an application configuration.
 */
export const deleteApiApplicationConfigurationsKey = (
  key: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.default.delete(`/api/application-configurations/${key}`, options);
};

export const getDeleteApiApplicationConfigurationsKeyMutationOptions = <
  TError = AxiosError<ProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiApplicationConfigurationsKey>>,
    TError,
    { key: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiApplicationConfigurationsKey>>,
  TError,
  { key: string },
  TContext
> => {
  const mutationKey = ['deleteApiApplicationConfigurationsKey'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiApplicationConfigurationsKey>>,
    { key: string }
  > = (props) => {
    const { key } = props ?? {};

    return deleteApiApplicationConfigurationsKey(key, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiApplicationConfigurationsKeyMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiApplicationConfigurationsKey>>
>;

export type DeleteApiApplicationConfigurationsKeyMutationError = AxiosError<ProblemDetails>;

/**
 * @summary Deletes an application configuration.
 */
export const useDeleteApiApplicationConfigurationsKey = <TError = AxiosError<ProblemDetails>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiApplicationConfigurationsKey>>,
      TError,
      { key: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiApplicationConfigurationsKey>>,
  TError,
  { key: string },
  TContext
> => {
  return useMutation(getDeleteApiApplicationConfigurationsKeyMutationOptions(options), queryClient);
};
