/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import * as axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  AiTemplateEnqueueResult,
  AiVideoTemplateRequest,
  CopyVideoTemplateRequest,
  GetVideosRequest,
  PostApiVideosResyncParams,
  ProblemDetails,
  UpdateVideoMetadataRequest,
  VideoDetailsDto,
  VideoListItemDtoPagedResult,
} from './..';

/**
 * @summary Copies video template metadata from source to target video using cached data.
 */
export const postApiVideosCopyTemplate = (
  copyVideoTemplateRequest: CopyVideoTemplateRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.default.post(`/api/videos/copy-template`, copyVideoTemplateRequest, options);
};

export const getPostApiVideosCopyTemplateMutationOptions = <
  TError = AxiosError<ProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiVideosCopyTemplate>>,
    TError,
    { data: CopyVideoTemplateRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiVideosCopyTemplate>>,
  TError,
  { data: CopyVideoTemplateRequest },
  TContext
> => {
  const mutationKey = ['postApiVideosCopyTemplate'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiVideosCopyTemplate>>,
    { data: CopyVideoTemplateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiVideosCopyTemplate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiVideosCopyTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiVideosCopyTemplate>>
>;
export type PostApiVideosCopyTemplateMutationBody = CopyVideoTemplateRequest;
export type PostApiVideosCopyTemplateMutationError = AxiosError<ProblemDetails>;

/**
 * @summary Copies video template metadata from source to target video using cached data.
 */
export const usePostApiVideosCopyTemplate = <TError = AxiosError<ProblemDetails>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiVideosCopyTemplate>>,
      TError,
      { data: CopyVideoTemplateRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiVideosCopyTemplate>>,
  TError,
  { data: CopyVideoTemplateRequest },
  TContext
> => {
  return useMutation(getPostApiVideosCopyTemplateMutationOptions(options), queryClient);
};
/**
 * @summary Improve video metadata using AI
 */
export const postApiVideosAiTemplate = (
  aiVideoTemplateRequest: AiVideoTemplateRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<AiTemplateEnqueueResult>> => {
  return axios.default.post(`/api/videos/ai-template`, aiVideoTemplateRequest, options);
};

export const getPostApiVideosAiTemplateMutationOptions = <
  TError = AxiosError<ProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiVideosAiTemplate>>,
    TError,
    { data: AiVideoTemplateRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiVideosAiTemplate>>,
  TError,
  { data: AiVideoTemplateRequest },
  TContext
> => {
  const mutationKey = ['postApiVideosAiTemplate'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiVideosAiTemplate>>,
    { data: AiVideoTemplateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiVideosAiTemplate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiVideosAiTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiVideosAiTemplate>>>;
export type PostApiVideosAiTemplateMutationBody = AiVideoTemplateRequest;
export type PostApiVideosAiTemplateMutationError = AxiosError<ProblemDetails>;

/**
 * @summary Improve video metadata using AI
 */
export const usePostApiVideosAiTemplate = <TError = AxiosError<ProblemDetails>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiVideosAiTemplate>>,
      TError,
      { data: AiVideoTemplateRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiVideosAiTemplate>>,
  TError,
  { data: AiVideoTemplateRequest },
  TContext
> => {
  return useMutation(getPostApiVideosAiTemplateMutationOptions(options), queryClient);
};
/**
 * @summary Gets a paginated list of videos with optional title and visibility filters.
 */
export const postApiVideosSearch = (
  getVideosRequest: GetVideosRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VideoListItemDtoPagedResult>> => {
  return axios.default.post(`/api/videos/search`, getVideosRequest, options);
};

export const getPostApiVideosSearchMutationOptions = <
  TError = AxiosError<ProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiVideosSearch>>,
    TError,
    { data: GetVideosRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiVideosSearch>>,
  TError,
  { data: GetVideosRequest },
  TContext
> => {
  const mutationKey = ['postApiVideosSearch'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiVideosSearch>>, { data: GetVideosRequest }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return postApiVideosSearch(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiVideosSearchMutationResult = NonNullable<Awaited<ReturnType<typeof postApiVideosSearch>>>;
export type PostApiVideosSearchMutationBody = GetVideosRequest;
export type PostApiVideosSearchMutationError = AxiosError<ProblemDetails>;

/**
 * @summary Gets a paginated list of videos with optional title and visibility filters.
 */
export const usePostApiVideosSearch = <TError = AxiosError<ProblemDetails>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiVideosSearch>>,
      TError,
      { data: GetVideosRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postApiVideosSearch>>, TError, { data: GetVideosRequest }, TContext> => {
  return useMutation(getPostApiVideosSearchMutationOptions(options), queryClient);
};
/**
 * @summary Gets video details (title, description, tags) for a single video.
 */
export const getApiVideosVideoId = (
  videoId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VideoDetailsDto>> => {
  return axios.default.get(`/api/videos/${videoId}`, options);
};

export const getGetApiVideosVideoIdQueryKey = (videoId: string) => {
  return [`/api/videos/${videoId}`] as const;
};

export const getGetApiVideosVideoIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiVideosVideoId>>,
  TError = AxiosError<ProblemDetails>,
>(
  videoId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVideosVideoId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiVideosVideoIdQueryKey(videoId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiVideosVideoId>>> = ({ signal }) =>
    getApiVideosVideoId(videoId, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!videoId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiVideosVideoId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiVideosVideoIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiVideosVideoId>>>;
export type GetApiVideosVideoIdQueryError = AxiosError<ProblemDetails>;

export function useGetApiVideosVideoId<
  TData = Awaited<ReturnType<typeof getApiVideosVideoId>>,
  TError = AxiosError<ProblemDetails>,
>(
  videoId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVideosVideoId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiVideosVideoId>>,
          TError,
          Awaited<ReturnType<typeof getApiVideosVideoId>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiVideosVideoId<
  TData = Awaited<ReturnType<typeof getApiVideosVideoId>>,
  TError = AxiosError<ProblemDetails>,
>(
  videoId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVideosVideoId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiVideosVideoId>>,
          TError,
          Awaited<ReturnType<typeof getApiVideosVideoId>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiVideosVideoId<
  TData = Awaited<ReturnType<typeof getApiVideosVideoId>>,
  TError = AxiosError<ProblemDetails>,
>(
  videoId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVideosVideoId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Gets video details (title, description, tags) for a single video.
 */

export function useGetApiVideosVideoId<
  TData = Awaited<ReturnType<typeof getApiVideosVideoId>>,
  TError = AxiosError<ProblemDetails>,
>(
  videoId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVideosVideoId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiVideosVideoIdQueryOptions(videoId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Updates a video's editable metadata (title, description, tags).
 */
export const postApiVideosUpdate = (
  updateVideoMetadataRequest: UpdateVideoMetadataRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VideoDetailsDto>> => {
  return axios.default.post(`/api/videos/update`, updateVideoMetadataRequest, options);
};

export const getPostApiVideosUpdateMutationOptions = <
  TError = AxiosError<ProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiVideosUpdate>>,
    TError,
    { data: UpdateVideoMetadataRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiVideosUpdate>>,
  TError,
  { data: UpdateVideoMetadataRequest },
  TContext
> => {
  const mutationKey = ['postApiVideosUpdate'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiVideosUpdate>>,
    { data: UpdateVideoMetadataRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiVideosUpdate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiVideosUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiVideosUpdate>>>;
export type PostApiVideosUpdateMutationBody = UpdateVideoMetadataRequest;
export type PostApiVideosUpdateMutationError = AxiosError<ProblemDetails>;

/**
 * @summary Updates a video's editable metadata (title, description, tags).
 */
export const usePostApiVideosUpdate = <TError = AxiosError<ProblemDetails>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiVideosUpdate>>,
      TError,
      { data: UpdateVideoMetadataRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiVideosUpdate>>,
  TError,
  { data: UpdateVideoMetadataRequest },
  TContext
> => {
  return useMutation(getPostApiVideosUpdateMutationOptions(options), queryClient);
};
/**
 * @summary Saves draft video metadata (title, description, tags) without submitting to YouTube.
 */
export const postApiVideosSaveDraft = (
  updateVideoMetadataRequest: UpdateVideoMetadataRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VideoDetailsDto>> => {
  return axios.default.post(`/api/videos/save-draft`, updateVideoMetadataRequest, options);
};

export const getPostApiVideosSaveDraftMutationOptions = <
  TError = AxiosError<ProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiVideosSaveDraft>>,
    TError,
    { data: UpdateVideoMetadataRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiVideosSaveDraft>>,
  TError,
  { data: UpdateVideoMetadataRequest },
  TContext
> => {
  const mutationKey = ['postApiVideosSaveDraft'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiVideosSaveDraft>>,
    { data: UpdateVideoMetadataRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiVideosSaveDraft(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiVideosSaveDraftMutationResult = NonNullable<Awaited<ReturnType<typeof postApiVideosSaveDraft>>>;
export type PostApiVideosSaveDraftMutationBody = UpdateVideoMetadataRequest;
export type PostApiVideosSaveDraftMutationError = AxiosError<ProblemDetails>;

/**
 * @summary Saves draft video metadata (title, description, tags) without submitting to YouTube.
 */
export const usePostApiVideosSaveDraft = <TError = AxiosError<ProblemDetails>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiVideosSaveDraft>>,
      TError,
      { data: UpdateVideoMetadataRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiVideosSaveDraft>>,
  TError,
  { data: UpdateVideoMetadataRequest },
  TContext
> => {
  return useMutation(getPostApiVideosSaveDraftMutationOptions(options), queryClient);
};
/**
 * @summary Resyncs a video's details and playlists from YouTube.
 */
export const postApiVideosResync = (
  params?: PostApiVideosResyncParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VideoDetailsDto>> => {
  return axios.default.post(`/api/videos/resync`, undefined, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getPostApiVideosResyncMutationOptions = <
  TError = AxiosError<ProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiVideosResync>>,
    TError,
    { params?: PostApiVideosResyncParams },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiVideosResync>>,
  TError,
  { params?: PostApiVideosResyncParams },
  TContext
> => {
  const mutationKey = ['postApiVideosResync'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiVideosResync>>,
    { params?: PostApiVideosResyncParams }
  > = (props) => {
    const { params } = props ?? {};

    return postApiVideosResync(params, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiVideosResyncMutationResult = NonNullable<Awaited<ReturnType<typeof postApiVideosResync>>>;

export type PostApiVideosResyncMutationError = AxiosError<ProblemDetails>;

/**
 * @summary Resyncs a video's details and playlists from YouTube.
 */
export const usePostApiVideosResync = <TError = AxiosError<ProblemDetails>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiVideosResync>>,
      TError,
      { params?: PostApiVideosResyncParams },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiVideosResync>>,
  TError,
  { params?: PostApiVideosResyncParams },
  TContext
> => {
  return useMutation(getPostApiVideosResyncMutationOptions(options), queryClient);
};
