/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */

export interface AiSuggestionOptions {
  promptEnrichment?: string;
  generateTitle?: boolean;
  generateDescription?: boolean;
  generateTags?: boolean;
}
