/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */

export interface AuthMeResponse {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  sub?: string | null;
  /** @nullable */
  channelId?: string | null;
  /** @nullable */
  channelTitle?: string | null;
  /** @nullable */
  picture?: string | null;
  hasWriteAccess?: boolean;
}
