/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */
import type { DraftDecisionResultDto } from './draftDecisionResultDto';

export interface BatchDecisionResultDto {
  total?: number;
  succeeded?: number;
  failed?: number;
  items?: DraftDecisionResultDto[];
}
