/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */

export interface BatchIgnoreResult {
  requested?: number;
  ignored?: number;
  alreadyIgnored?: number;
  skippedPosted?: number;
  notFound?: number;
  ignoredIds?: string[];
  alreadyIgnoredIds?: string[];
  skippedPostedIds?: string[];
  notFoundIds?: string[];
}
