/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */

export interface ChannelSettingsDto {
  channelId?: string;
  isCommentAssistantEnabled?: boolean;
  isSuggestRepliesForTopLevelCommentsOnly?: boolean;
  maxSuggestedRepliesPerSync?: number;
  maxCommentAgeDays?: number;
  replyLanguage?: string;
  /** @nullable */
  responseForNonTextualComments?: string | null;
  updatedAtUtc?: string;
}
