/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */

export interface ChannelSyncResult {
  videosInserted?: number;
  videosUpdated?: number;
  playlistsInserted?: number;
  playlistsUpdated?: number;
  membershipsAdded?: number;
  membershipsRemoved?: number;
}
