/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */

export interface Channel {
  readonly channelId?: string;
  readonly name?: string;
  readonly uploadsPlaylistId?: string;
  /** @nullable */
  readonly eTag?: string | null;
  readonly updatedAt?: string;
  /** @nullable */
  readonly lastUploadsCutoff?: string | null;
}
