/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */

export interface Channel {
  readonly channelId?: string;
  readonly userId?: string;
  readonly name?: string;
  readonly uploadsPlaylistId?: string;
  /** @nullable */
  readonly eTag?: string | null;
  readonly updatedAt?: string;
  /** @nullable */
  readonly lastUploadsCutoff?: string | null;
}
