/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import type { AiSuggestionOptions } from './aiSuggestionOptions';

export interface CopyVideoTemplateRequest {
  sourceVideoId?: string;
  targetVideoId?: string;
  copyTags?: boolean;
  copyLocation?: boolean;
  copyPlaylists?: boolean;
  copyCategory?: boolean;
  copyDefaultLanguages?: boolean;
  aiSuggestionOptions?: AiSuggestionOptions;
}
