/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */
import type { ReplyStatus } from './replyStatus';

export type GetApiRepliesParams = {
statuses?: ReplyStatus[];
pageSize?: number;
pageToken?: string;
};
