/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import type { VideoVisibility } from './videoVisibility';

export type GetApiVideosParams = {
  /**
   * Case-insensitive substring filter for video titles.
   */
  title?: string;
  /**
 * Optional visibility filter. Multiple values allowed
(`?visibility=Public&visibility=Unlisted`).
Accepts enum names or numeric values (Public=0, Unlisted=1, Private=2, Scheduled=3).
 */
  visibility?: VideoVisibility[];
  /**
   * Items per page (1–100, default 30).
   */
  pageSize?: number;
  /**
   * Cursor token for pagination, or `null` for first page.
   */
  pageToken?: string;
};
