/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */
import type { VideoVisibility } from './videoVisibility';

export type GetApiVideosParams = {
/**
 * Case-insensitive substring filter for video titles.
 */
title?: string;
/**
 * Optional visibility filter. Multiple values allowed 
(`?visibility=Public&visibility=Unlisted`). 
Accepts enum names or numeric values (Public=0, Unlisted=1, Private=2, Scheduled=3).
 */
visibility?: VideoVisibility[];
/**
 * Items per page (1–100, default 30).
 */
pageSize?: number;
/**
 * Cursor token for pagination, or `null` for first page.
 */
pageToken?: string;
};
