/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import type { VideoVisibility } from './videoVisibility';

export interface GetVideosRequest {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  visibility?: VideoVisibility[] | null;
  /** @nullable */
  pageSize?: number | null;
  /** @nullable */
  pageToken?: string | null;
}
