/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester API
 * To access protected endpoints, first log in:

[🔐 Login with Google](/auth/login/google?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  [key: string]: unknown;
}
