/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */
import type { ReplyStatus } from './replyStatus';

export interface Reply {
  readonly commentId?: string;
  readonly videoId?: string;
  readonly videoTitle?: string;
  readonly commentText?: string;
  status?: ReplyStatus;
  /** @nullable */
  readonly suggestedText?: string | null;
  /** @nullable */
  readonly finalText?: string | null;
  readonly pulledAt?: string;
  /** @nullable */
  readonly suggestedAt?: string | null;
  /** @nullable */
  readonly approvedAt?: string | null;
  /** @nullable */
  readonly postedAt?: string | null;
}
