/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import type { ReplyStatus } from './replyStatus';

export interface Reply {
  readonly commentId?: string;
  readonly videoId?: string;
  readonly videoTitle?: string;
  readonly commentText?: string;
  status?: ReplyStatus;
  /** @nullable */
  readonly suggestedText?: string | null;
  /** @nullable */
  readonly finalText?: string | null;
  readonly pulledAt?: string;
  /** @nullable */
  readonly suggestedAt?: string | null;
  /** @nullable */
  readonly approvedAt?: string | null;
  /** @nullable */
  readonly postedAt?: string | null;
}
