/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */

export interface ReplyListItemDto {
  commentId: string;
  videoId: string;
  /** @nullable */
  videoTitle?: string | null;
  /** @nullable */
  commentText?: string | null;
  thumbnailUrl: string;
  /** @nullable */
  originalCommentAt?: string | null;
  /** @nullable */
  suggestedText?: string | null;
}
