/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */

export type ReplyStatus = typeof ReplyStatus[keyof typeof ReplyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReplyStatus = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;
