/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */
import type { ReplyListItemDto } from './replyListItemDto';

export interface ReplyListItemDtoPagedResult {
  /** @nullable */
  items: ReplyListItemDto[] | null;
  /** @nullable */
  nextPageToken?: string | null;
}
