/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */
import type { ReplyStatus } from './replyStatus';

export interface ReplyListItemDto {
  /** @nullable */
  commentId: string | null;
  /** @nullable */
  videoId: string | null;
  /** @nullable */
  videoTitle: string | null;
  /** @nullable */
  commentText: string | null;
  status: ReplyStatus;
  pulledAt: string;
  /** @nullable */
  suggestedAt?: string | null;
  /** @nullable */
  approvedAt?: string | null;
  /** @nullable */
  postedAt?: string | null;
}
