/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester API
 * To access protected endpoints, first log in:

[🔐 Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */

export interface UserChannelDto {
  id?: string;
  title?: string;
  /** @nullable */
  picture?: string | null;
}
