/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */

export interface VideoListItemDto {
  videoId: string;
  /** @nullable */
  title?: string | null;
  publishedAt?: string;
  thumbnailUrl: string;
}
