/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import type { GeoLocationDto } from './geoLocationDto';
import type { PlaylistDto } from './playlistDto';
import type { CategoryDto } from './categoryDto';

export interface VideoDetailsDto {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  tags: string[];
  isAiTemplateInProgress?: boolean;
  location?: GeoLocationDto;
  /** @nullable */
  locationDescription?: string | null;
  playlists: PlaylistDto[];
  category?: CategoryDto;
  /** @nullable */
  defaultLanguage?: string | null;
  /** @nullable */
  defaultAudioLanguage?: string | null;
}
