/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */

export interface VideoListItemDto {
  /** @nullable */
  videoId: string | null;
  /** @nullable */
  title?: string | null;
  publishedAt?: string;
  /** @nullable */
  thumbnailUrl: string | null;
}
