/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */
import type { VideoListItemDto } from './videoListItemDto';

export interface VideoListItemDtoPagedResult {
  /** @nullable */
  items: VideoListItemDto[] | null;
  /** @nullable */
  nextPageToken?: string | null;
}
