/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */

export type VideoVisibility = typeof VideoVisibility[keyof typeof VideoVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VideoVisibility = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
