/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */
import type { AiSuggestionOptions } from './aiSuggestionOptions';

export interface CopyVideoTemplateRequest {
  /** @nullable */
  sourceUrl?: string | null;
  /** @nullable */
  targetUrl?: string | null;
  copyTags?: boolean;
  copyLocation?: boolean;
  copyPlaylists?: boolean;
  copyCategory?: boolean;
  copyDefaultLanguages?: boolean;
  aiSuggestionOptions?: AiSuggestionOptions;
}
