/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */

export interface DraftDecisionDto {
  /** @nullable */
  commentId?: string | null;
  /** @nullable */
  approvedText?: string | null;
}
