/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ActionResult,
  ProblemDetails
} from '.././';





/**
 * @summary Registers the gob to pull the comments
 */
export const getApiComentsPull = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ActionResult>> => {
    
    
    return axios.default.get(
      `/api/coments/pull`,options
    );
  }




export const getGetApiComentsPullQueryKey = () => {
    return [
    `/api/coments/pull`
    ] as const;
    }

    
export const getGetApiComentsPullQueryOptions = <TData = Awaited<ReturnType<typeof getApiComentsPull>>, TError = AxiosError<ProblemDetails>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiComentsPull>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiComentsPullQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiComentsPull>>> = ({ signal }) => getApiComentsPull({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiComentsPull>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiComentsPullQueryResult = NonNullable<Awaited<ReturnType<typeof getApiComentsPull>>>
export type GetApiComentsPullQueryError = AxiosError<ProblemDetails>


export function useGetApiComentsPull<TData = Awaited<ReturnType<typeof getApiComentsPull>>, TError = AxiosError<ProblemDetails>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiComentsPull>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiComentsPull>>,
          TError,
          Awaited<ReturnType<typeof getApiComentsPull>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiComentsPull<TData = Awaited<ReturnType<typeof getApiComentsPull>>, TError = AxiosError<ProblemDetails>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiComentsPull>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiComentsPull>>,
          TError,
          Awaited<ReturnType<typeof getApiComentsPull>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiComentsPull<TData = Awaited<ReturnType<typeof getApiComentsPull>>, TError = AxiosError<ProblemDetails>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiComentsPull>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Registers the gob to pull the comments
 */

export function useGetApiComentsPull<TData = Awaited<ReturnType<typeof getApiComentsPull>>, TError = AxiosError<ProblemDetails>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiComentsPull>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiComentsPullQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




