/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * YouTubester.Api
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Channel,
  ChannelSyncResult,
  ProblemDetails
} from '.././';





/**
 * @summary Pulls channel metadata from YouTube (by name)
 */
export const postApiChannelsPullChannelName = (
    channelName: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Channel>> => {
    
    
    return axios.default.post(
      `/api/channels/pull/${channelName}`,undefined,options
    );
  }



export const getPostApiChannelsPullChannelNameMutationOptions = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiChannelsPullChannelName>>, TError,{channelName: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiChannelsPullChannelName>>, TError,{channelName: string}, TContext> => {

const mutationKey = ['postApiChannelsPullChannelName'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiChannelsPullChannelName>>, {channelName: string}> = (props) => {
          const {channelName} = props ?? {};

          return  postApiChannelsPullChannelName(channelName,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiChannelsPullChannelNameMutationResult = NonNullable<Awaited<ReturnType<typeof postApiChannelsPullChannelName>>>
    
    export type PostApiChannelsPullChannelNameMutationError = AxiosError<ProblemDetails>

    /**
 * @summary Pulls channel metadata from YouTube (by name)
 */
export const usePostApiChannelsPullChannelName = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiChannelsPullChannelName>>, TError,{channelName: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiChannelsPullChannelName>>,
        TError,
        {channelName: string},
        TContext
      > => {

      const mutationOptions = getPostApiChannelsPullChannelNameMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Runs full sync for a channel by name.
 */
export const postApiChannelsSyncChannelName = (
    channelName: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ChannelSyncResult>> => {
    
    
    return axios.default.post(
      `/api/channels/sync/${channelName}`,undefined,options
    );
  }



export const getPostApiChannelsSyncChannelNameMutationOptions = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiChannelsSyncChannelName>>, TError,{channelName: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiChannelsSyncChannelName>>, TError,{channelName: string}, TContext> => {

const mutationKey = ['postApiChannelsSyncChannelName'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiChannelsSyncChannelName>>, {channelName: string}> = (props) => {
          const {channelName} = props ?? {};

          return  postApiChannelsSyncChannelName(channelName,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiChannelsSyncChannelNameMutationResult = NonNullable<Awaited<ReturnType<typeof postApiChannelsSyncChannelName>>>
    
    export type PostApiChannelsSyncChannelNameMutationError = AxiosError<ProblemDetails>

    /**
 * @summary Runs full sync for a channel by name.
 */
export const usePostApiChannelsSyncChannelName = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiChannelsSyncChannelName>>, TError,{channelName: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiChannelsSyncChannelName>>,
        TError,
        {channelName: string},
        TContext
      > => {

      const mutationOptions = getPostApiChannelsSyncChannelNameMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    