/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ChannelSettingsDto,
  ProblemDetails,
  UpdateChannelSettingsRequest,
  ValidationProblemDetails
} from '.././';





/**
 * @summary Returns the comment assistant settings for the specified channel.
If settings do not exist yet, they are created with defaults.
 */
export const getApiChannelSettings = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ChannelSettingsDto>> => {
    
    
    return axios.default.get(
      `/api/channel-settings`,options
    );
  }




export const getGetApiChannelSettingsQueryKey = () => {
    return [
    `/api/channel-settings`
    ] as const;
    }

    
export const getGetApiChannelSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getApiChannelSettings>>, TError = AxiosError<ProblemDetails>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiChannelSettings>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiChannelSettingsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiChannelSettings>>> = ({ signal }) => getApiChannelSettings({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiChannelSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiChannelSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiChannelSettings>>>
export type GetApiChannelSettingsQueryError = AxiosError<ProblemDetails>


export function useGetApiChannelSettings<TData = Awaited<ReturnType<typeof getApiChannelSettings>>, TError = AxiosError<ProblemDetails>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiChannelSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiChannelSettings>>,
          TError,
          Awaited<ReturnType<typeof getApiChannelSettings>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiChannelSettings<TData = Awaited<ReturnType<typeof getApiChannelSettings>>, TError = AxiosError<ProblemDetails>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiChannelSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiChannelSettings>>,
          TError,
          Awaited<ReturnType<typeof getApiChannelSettings>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiChannelSettings<TData = Awaited<ReturnType<typeof getApiChannelSettings>>, TError = AxiosError<ProblemDetails>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiChannelSettings>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns the comment assistant settings for the specified channel.
If settings do not exist yet, they are created with defaults.
 */

export function useGetApiChannelSettings<TData = Awaited<ReturnType<typeof getApiChannelSettings>>, TError = AxiosError<ProblemDetails>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiChannelSettings>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiChannelSettingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Fully updates the comment assistant settings for the specified channel.
 */
export const putApiChannelSettings = (
    updateChannelSettingsRequest: UpdateChannelSettingsRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ChannelSettingsDto>> => {
    
    
    return axios.default.put(
      `/api/channel-settings`,
      updateChannelSettingsRequest,options
    );
  }



export const getPutApiChannelSettingsMutationOptions = <TError = AxiosError<ValidationProblemDetails | ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiChannelSettings>>, TError,{data: UpdateChannelSettingsRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putApiChannelSettings>>, TError,{data: UpdateChannelSettingsRequest}, TContext> => {

const mutationKey = ['putApiChannelSettings'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiChannelSettings>>, {data: UpdateChannelSettingsRequest}> = (props) => {
          const {data} = props ?? {};

          return  putApiChannelSettings(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiChannelSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof putApiChannelSettings>>>
    export type PutApiChannelSettingsMutationBody = UpdateChannelSettingsRequest
    export type PutApiChannelSettingsMutationError = AxiosError<ValidationProblemDetails | ProblemDetails>

    /**
 * @summary Fully updates the comment assistant settings for the specified channel.
 */
export const usePutApiChannelSettings = <TError = AxiosError<ValidationProblemDetails | ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiChannelSettings>>, TError,{data: UpdateChannelSettingsRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiChannelSettings>>,
        TError,
        {data: UpdateChannelSettingsRequest},
        TContext
      > => {

      const mutationOptions = getPutApiChannelSettingsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    